In [1]:
import pandas as pd

In [4]:
df = pd.read_json('../data/aeroplane_model.json')

In [5]:
df

,Boeing,Airbus,Embraer,Bombardier,Cessna,Gulfstream,Dassault,Mitsubishi,COMAC
737-800,"{'max_seats': 189, 'max_weight': 79015, 'max_d...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
777-300ER,"{'max_seats': 396, 'max_weight': 351535, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
787-9,"{'max_seats': 296, 'max_weight': 254000, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A320neo,NaN,"{'max_seats': 194, 'max_weight': 79000, 'max_d...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
A350-900,NaN,"{'max_seats': 440, 'max_weight': 280000, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
A380-800,NaN,"{'max_seats': 853, 'max_weight': 560000, 'max_...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
E190-E2,NaN,NaN,"{'max_seats': 114, 'max_weight': 56600, 'max_d...",NaN,NaN,NaN,NaN,NaN,NaN
E175,NaN,NaN,"{'max_seats': 88, 'max_weight': 37500, 'max_di...",NaN,NaN,NaN,NaN,NaN,NaN
E195-E2,NaN,NaN,"{'max_seats': 146, 'max_weight': 61700, 'max_d...",NaN,NaN,NaN,NaN,NaN,NaN
CRJ900,NaN,NaN,NaN,"{'max_seats': 90, 'max_weight': 38530, 'max_di...",NaN,NaN,NaN,NaN,NaN
Q400,NaN,NaN,NaN,"{'max_seats': 90, 'max_weight': 29257, 'max_di...",NaN,NaN,NaN,NaN,NaN
Citation X+,NaN,NaN,NaN,NaN,"{'max_seats': 12, 'max_weight': 16555, 'max_di...",NaN,NaN,NaN,NaN
Citation Latitude,NaN,NaN,NaN,NaN,"{'max_seats': 9, 'max_weight': 13605, 'max_dis...",NaN,NaN,NaN,NaN
G650,NaN,NaN,NaN,NaN,NaN,"{'max_seats': 19, 'max_weight': 45360, 'max_di...",NaN,NaN,NaN
G550,NaN,NaN,NaN,NaN,NaN,"{'max_seats': 19, 'max_weight': 41300, 'max_di...",NaN,NaN,NaN
Falcon 7X,NaN,NaN,NaN,NaN,NaN,NaN,"{'max_seats': 19, 'max_weight': 31750, 'max_di...",NaN,NaN
Falcon 2000LXS,NaN,NaN,NaN,NaN,NaN,NaN,"{'max_seats': 10, 'max_weight': 19105, 'max_di...",NaN,NaN
SpaceJet M90,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'max_seats': 92, 'max_weight': 39000, 'max_di...",NaN
C919,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"{'max_seats': 174, 'max_weight': 72500, 'max_d..."

In [6]:
import json

with open('../data/aeroplane_model.json') as f:
    d = json.load(f)
    print(d)

{'Boeing': {'737-800': {'max_seats': 189, 'max_weight': 79015, 'max_distance': 2935, 'engine_type': 'CFM56-7B'}, '777-300ER': {'max_seats': 396, 'max_weight': 351535, 'max_distance': 7930, 'engine_type': 'GE90-115B'}, '787-9': {'max_seats': 296, 'max_weight': 254000, 'max_distance': 7635, 'engine_type': 'GEnx-1B'}}, 'Airbus': {'A320neo': {'max_seats': 194, 'max_weight': 79000, 'max_distance': 3700, 'engine_type': 'CFM LEAP-1A'}, 'A350-900': {'max_seats': 440, 'max_weight': 280000, 'max_distance': 8100, 'engine_type': 'Rolls-Royce Trent XWB'}, 'A380-800': {'max_seats': 853, 'max_weight': 560000, 'max_distance': 8000, 'engine_type': 'Rolls-Royce Trent 900'}}, 'Embraer': {'E190-E2': {'max_seats': 114, 'max_weight': 56600, 'max_distance': 3250, 'engine_type': 'PW1900G'}, 'E175': {'max_seats': 88, 'max_weight': 37500, 'max_distance': 2200, 'engine_type': 'CF34-8E'}, 'E195-E2': {'max_seats': 146, 'max_weight': 61700, 'max_distance': 2600, 'engine_type': 'PW1900G'}}, 'Bombardier': {'CRJ900': {'max_seats': 90, 'max_weight': 38530, 'max_distance': 1554, 'engine_type': 'CF34-8C5'}, 'Q400': {'max_seats': 90, 'max_weight': 29257, 'max_distance': 1567, 'engine_type': 'PW150A'}}, 'Cessna': {'Citation X+': {'max_seats': 12, 'max_weight': 16555, 'max_distance': 3516, 'engine_type': 'AE3007C2'}, 'Citation Latitude': {'max_seats': 9, 'max_weight': 13605, 'max_distance': 2700, 'engine_type': 'PW306D1'}}, 'Gulfstream': {'G650': {'max_seats': 19, 'max_weight': 45360, 'max_distance': 7500, 'engine_type': 'BR725'}, 'G550': {'max_seats': 19, 'max_weight': 41300, 'max_distance': 6750, 'engine_type': 'BR710'}}, 'Dassault': {'Falcon 7X': {'max_seats': 19, 'max_weight': 31750, 'max_distance': 5950, 'engine_type': 'PW307A'}, 'Falcon 2000LXS': {'max_seats': 10, 'max_weight': 19105, 'max_distance': 4000, 'engine_type': 'PW308C'}}, 'Mitsubishi': {'SpaceJet M90': {'max_seats': 92, 'max_weight': 39000, 'max_distance': 2030, 'engine_type': 'PW1200G'}}, 'COMAC': {'C919': {'max_seats': 174, 'max_weight': 72500, 'max_distance': 2555, 'engine_type': 'CFM LEAP-1C'}}}

In [35]:
fleet = []

In [36]:
for item in d:
    aeroplane = {}
    print(item)
    aeroplane['type'] = item
    for indi in d[item]:
        aeroplane['series'] = indi
        aeroplane['max_seats'] = d[item][indi]['max_seats']
        aeroplane['max_weight'] = d[item][indi]['max_weight']
        aeroplane['max_distance'] = d[item][indi]['max_distance']
        aeroplane['engine_type'] = d[item][indi]['engine_type']
    fleet.append(aeroplane)

Boeing
Airbus
Embraer
Bombardier
Cessna
Gulfstream
Dassault
Mitsubishi
COMAC

In [37]:
fleet

[{'type': 'Boeing',
  'series': '787-9',
  'max_seats': 296,
  'max_weight': 254000,
  'max_distance': 7635,
  'engine_type': 'GEnx-1B'},
 {'type': 'Airbus',
  'series': 'A380-800',
  'max_seats': 853,
  'max_weight': 560000,
  'max_distance': 8000,
  'engine_type': 'Rolls-Royce Trent 900'},
 {'type': 'Embraer',
  'series': 'E195-E2',
  'max_seats': 146,
  'max_weight': 61700,
  'max_distance': 2600,
  'engine_type': 'PW1900G'},
 {'type': 'Bombardier',
  'series': 'Q400',
  'max_seats': 90,
  'max_weight': 29257,
  'max_distance': 1567,
  'engine_type': 'PW150A'},
 {'type': 'Cessna',
  'series': 'Citation Latitude',
  'max_seats': 9,
  'max_weight': 13605,
  'max_distance': 2700,
  'engine_type': 'PW306D1'},
 {'type': 'Gulfstream',
  'series': 'G550',
  'max_seats': 19,
  'max_weight': 41300,
  'max_distance': 6750,
  'engine_type': 'BR710'},
 {'type': 'Dassault',
  'series': 'Falcon 2000LXS',
  'max_seats': 10,
  'max_weight': 19105,
  'max_distance': 4000,
  'engine_type': 'PW308C'},
 {'type': 'Mitsubishi',
  'series': 'SpaceJet M90',
  'max_seats': 92,
  'max_weight': 39000,
  'max_distance': 2030,
  'engine_type': 'PW1200G'},
 {'type': 'COMAC',
  'series': 'C919',
  'max_seats': 174,
  'max_weight': 72500,
  'max_distance': 2555,
  'engine_type': 'CFM LEAP-1C'}]

In [38]:
df = pd.DataFrame(fleet)
df

,type,series,max_seats,max_weight,max_distance,engine_type
0,Boeing,787-9,296,254000,7635,GEnx-1B
1,Airbus,A380-800,853,560000,8000,Rolls-Royce Trent 900
2,Embraer,E195-E2,146,61700,2600,PW1900G
3,Bombardier,Q400,90,29257,1567,PW150A
4,Cessna,Citation Latitude,9,13605,2700,PW306D1
5,Gulfstream,G550,19,41300,6750,BR710
6,Dassault,Falcon 2000LXS,10,19105,4000,PW308C
7,Mitsubishi,SpaceJet M90,92,39000,2030,PW1200G
8,COMAC,C919,174,72500,2555,CFM LEAP-1C

In [44]:
from sqlalchemy import text
from sqlalchemy import create_engine
engine = create_engine('sqlite:///air_boltic.db', echo=False)
with engine.connect() as conn:
   conn.execute(text("SELECT * FROM aeroplane_models")).fetchall()

OperationalError: (sqlite3.OperationalError) no such table: aeroplane_models
[SQL: SELECT * FROM aeroplane_models]
(Background on this error at: https://sqlalche.me/e/20/e3q8)